# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('show_in_left', models.BooleanField(default=True)),
                ('is_must', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cmdb_ci_category',
            },
        ),
        migrations.CreateModel(
            name='CiProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('form_type', models.CharField(choices=[('optional', '\u53ef\u9009'), ('required', '\u5fc5\u586b')], default='optional', max_length=30)),
                ('value_type', models.CharField(choices=[('num', '\u6570\u503c'), ('str', '\u5b57\u7b26'), ('array', '\u6570\u7ec4')], default='str', max_length=30)),
                ('is_must', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=True)),
                ('show_in_table', models.BooleanField(default=True)),
                ('is_search', models.BooleanField(default=True)),
                ('optional_value', models.TextField(blank=True, null=True)),
                ('ci_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CiCategory')),
            ],
            options={
                'db_table': 'cmdb_ci_property',
            },
        ),
    ]
