# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
